//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalTipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalTipos()
        {
            this.Personal = new HashSet<Personal>();
        }
    
        public byte IdPersonalTipo { get; set; }
        public string PersonalTipoDescripcion { get; set; }
        public bool IsPersonalLaboral { get; set; }
        public Nullable<byte> IdSueldosTabulacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal { get; set; }
        public virtual SueldoTabulaciones SueldosTabulacion { get; set; }
    }
}
